export const UI_STRINGS = {
	appName: 'HaloSanak',
	tagline: 'Pohon Keluarga Besar',
	nav: {
		tree: 'Pohon',
		members: 'Anggota',
		add: 'Tambah',
		settings: 'Pengaturan'
	},
	common: {
		save: 'Simpan',
		cancel: 'Batal',
		delete: 'Hapus',
		edit: 'Edit',
		back: 'Kembali',
		loading: 'Memproses...',
		close: 'Tutup',
		detail: 'Detail Anggota'
	},
	member: {
		fullName: 'Nama Lengkap',
		gender: 'Jenis Kelamin',
		male: 'Laki-laki',
		female: 'Perempuan',
		domicile: 'Domisili',
		birthDate: 'Tanggal Lahir',
		isDeceased: 'Sudah Wafat',
		deathDate: 'Tanggal Wafat',
		occupation: 'Pekerjaan',
		description: 'Deskripsi',
		birthOrder: 'Anak ke-berapa',
		birthOrderPlaceholder: 'Contoh: 1',
		birthOrderInvalid: 'Anak ke-berapa harus berupa angka bulat positif.',
		photoFailed: 'Foto tidak dapat diproses. Anda tetap dapat menyimpan profil tanpa foto.',
		nameRequired: 'Nama lengkap wajib diisi.',
		domicileRequired: 'Domisili wajib diisi.',
		saveFailed: 'Terjadi kesalahan saat menyimpan data.',
		photo: 'Foto Profil',
		age: 'Usia',
		yearsOld: 'tahun',
		deceasedBadge: 'Sudah wafat'
	},
	relations: {
		father: 'Ayah',
		mother: 'Ibu',
		spouse: 'Pasangan',
		children: 'Anak',
		noRelations: 'Belum ada relasi terhubung'
	},
	kinship: {
		calculateKinshipBtn: 'Hitung Hubungan',
		modalTitle: 'Hitung Hubungan Kekerabatan',
		selectTargetTitle: 'Pilih Anggota Target',
		searchPlaceholder: 'Cari nama anggota target...',
		viewPath: 'Lihat jalur silsilah',
		hidePath: 'Sembunyikan jalur silsilah',
		notFound: 'Tidak ditemukan hubungan langsung dari data yang tersedia',
		self: 'Diri sendiri',
		child: 'Anak',
		parent: 'Orang Tua',
		grandchild: 'Cucu',
		grandfather: 'Kakek',
		grandmother: 'Nenek',
		greatGrandchild: 'Cicit',
		greatGrandparent: 'Buyut',
		descendantGenN: (n: number) => `Keturunan generasi ke-${n}`,
		ancestorGenN: (n: number) => `Leluhur generasi ke-${n}`,
		olderSibling: 'Kakak',
		youngerSibling: 'Adik',
		fullSibling: 'Saudara Kandung',
		halfSibling: 'Saudara Tiri',
		nephewNiece: 'Keponakan',
		uncle: 'Paman',
		aunt: 'Bibi',
		cousin: 'Sepupu',
		distantCousin: 'Sepupu Jauh'
	},
	settings: {
		exportJSON: 'Export JSON',
		importJSON: 'Import JSON',
		clearAll: 'Hapus Semua Data',
		confirmClearTitle: 'Hapus Semua Data?',
		confirmClearWarning: 'Tindakan ini akan menghapus seluruh data lokal secara permanen.',
		permissionMissing: 'Izin notifikasi belum diberikan pada peramban ini.',
		notificationsEnabled: 'Notifikasi pengingat diaktifkan.',
		notificationsDisabled: 'Notifikasi pengingat dinonaktifkan.',
		remindersTitle: 'Peringatan & Pengingat',
		remindersSubtitle: 'Daftar peringatan ulang tahun dan peringatan wafat dalam 7 hari ke depan.',
		enableNotifications: 'Aktifkan Notifikasi Pengingat',
		notificationsDisclaimer: 'Pengingat bersifat best-effort pada peramban yang mendukung. Pada perangkat iPhone/iPad (iOS), tambahkan web app ini ke Layar Utama (Home Screen) terlebih dahulu agar peramban mengaktifkan izin notifikasi.',
		notificationsUnsupported: 'Peramban ini belum mendukung Web Notification API. Untuk pengguna iPhone/iPad, pasang web app ke Layar Utama (Add to Home Screen) untuk mencoba mengaktifkan fitur ini.',
		noUpcomingEvents: 'Tidak ada agenda ulang tahun atau peringatan wafat dalam 7 hari ke depan.'
	},
	errors: {
		invalidGraph: 'Integritas graph keluarga rusak: periksa siklus leluhur, gender, orang tua, pasangan, dan duplikat.',
		loadFailed: 'Gagal memuat data. Tutup dan coba lagi.',
		notificationStorage: 'Preferensi notifikasi gagal disimpan.',
		cycleDetected: 'Relasi ditolak: terdeteksi siklus leluhur.',
		cannotDeleteWithRelations: 'Anggota tidak dapat dihapus karena masih memiliki relasi aktif.',
		importFailed: 'File tidak valid atau format rusak.'
	},
	success: {
		saved: 'Data berhasil disimpan',
		exported: 'Data berhasil diexport',
		imported: 'Data berhasil diimport',
		deleted: 'Data berhasil dihapus'
	}
} as const;
